labels:
  platform: linux/amd64

variables:
  - &backend_options
    kubernetes:
      serviceAccountName: "cora-woodpecker-sa"
      securityContext:
        privileged: true

when:
  - event: [pull_request, manual]

steps:
  typecheck:
    image: img.cora.tools/dockerhub/library/node:20-alpine
    commands:
      - npm ci
      - npm run typecheck
      - npm run build
    backend_options:
      <<: *backend_options
